### ISSUE TITLE
Standardize naming of filenames

### ISSUE THREAD

**Issue by edewit** [openshiftio/appdev-documentation#188]
In order for the frontend to link to the booster doc of the project that was just created it would be nice if it could create the link based on the selected booster, right now the names are not the same, e.g.
_mission-health-check-spring-boot-tomcat_ and
_mission-secured-spring-boot_

we should rename `spring-boot` to `spring-boot-tomcat` as that is used more

**Comment by rhoads-zach** [comment]
@starksm64 can you you take a look at this?

**Comment by starksm64** [comment]
I can do that, but then the actual mission guide html name should be:

GUIDE_HTML_NAME=mission-secured-spring-boot-tomcat.html

and this would require an update of the https://github.com/snowdrop/spring-boot-http-secured-booster/blob/master/README.md booster in order to correct the link it has to the mission docs.

Is there a way to have a legacy redirect from http://appdev.openshift.io/docs/mission-secured-spring-boot.html to http://appdev.openshift.io/docs/mission-secured-spring-boot-tomcat.html?

**Comment by rhoads-zach** [comment]
All Spring Boot missions now located here:
http://appdev.openshift.io/docs/spring-boot-runtime.html
