### ISSUE TITLE
Review and finalize Vert.x missions interaction

### ISSUE THREAD

**Issue by rhoads-zach** [openshiftio/appdev-documentation#42]
https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/rest-level-0-experience-basic-interaction-vertx.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/health-check-experience-basic-interaction-vertx.adoc

https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-basic-interaction-vertx.adoc

**Comment by cescoffier** [comment]
In https://github.com/openshiftio/appdev-documentation/blob/master/docs/topics/configmap-experience-basic-interaction-vertx.adoc:

It

1.  references Spring Boot
2. Does not use the right way to push the new config map
3. As booster are going to have "health checks", I don't get the step 4.

**Comment by cescoffier** [comment]
Has been validated the health check mission ? It's still expose a microservice anti-pattern.

**Comment by cescoffier** [comment]
@rhoads-zach See my comments

**Comment by rhoads-zach** [comment]
@cescoffier 

Per the README, i see it references editing the configmap yml file directly and doing:

`oc apply -f src/main/fabric8/configmap.yml`

Is that the proper approach?  is the following not supported?

```
$ oc edit configmap app-config
$ oc rollout latest dc/{app-name}
```

How does this sync up with the other boosters in the mission? The mission write up is high level when updating the configmap and rolling it out:
https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap

When you update a configmap on a booster with health check, what is the proper way to see that the application has the latest configmap? In the current version of the doc, you just wait for the app to restart.

With respect to the Spring Boot reference, that has been fixed

**Comment by cescoffier** [comment]
@rhoads-zach 

During the initial deployment, the config map is provisioned automatically - it's clearly not recommended (config has its own lifecycle), but eases the interaction with the booster.

Afterward, to modify the configmap, the user needs to update `src/main/fabric8/configmap.yaml` and then apply it with `oc apply -f ....`. Nothing else is required, and so no rollout. Vert.x picks config change at runtime. Vert.x uses a different strategy, it does not need re-running the deployment process. In other words, the following commands are runtime specific (Swarm, SB):

```
$ oc edit configmap app-config
$ oc rollout latest dc/{app-name}
```

Looking at the description of the mission, it seems that the config map is now provisioned individually (as I said, we don't do that in Vert.x but that's doable). We don't use the same name either. The high-level description should not mention the rollout, just use runtime specific instructions to apply the changes.

As there is no restart, no problem with health checks, the configuration will be reloaded automatically and used. This happens a few seconds after the update (should be less than 2 seconds). Because of the threading model of Vert.x (single threaded), there is no need for quiescence when applying the new configuration.

**Comment by heiko-braun** [comment]
@cescoffier 

> During the initial deployment, the config map is provisioned automatically - it's clearly not recommended (config has its own lifecycle), but eases the interaction with the booster.

As per https://github.com/openshiftio/appdev-documentation/wiki/Mission:-ConfigMap spec the initial configmap should be created explicitly to make clear that it's a separate, independent entity:

```
oc create configmap <config_name> --from-file=app-config.yml
```

**Comment by cescoffier** [comment]
@heiko-braun so the springboot and vert.x booster need to be updated as they deploy the config map with the application (https://github.com/snowdrop/spring-boot-configmap-booster/blob/master/src/main/fabric8/configmap.yml).

But again for Vert.x `oc edit configmap app-config` is enough. Don't do a rollout. It's a reactive application, it reacts to change.

**Comment by cescoffier** [comment]
See issue reported in #95, #94, #98

**Comment by rhoads-zach** [comment]
@heiko-braun @cescoffier 

I have merged the linked issues from @cescoffier, is this conversation still ongoing, or is it considered resolved?

**Comment by heiko-braun** [comment]
I'll leave it to @cescoffier to take a final decision

**Comment by cescoffier** [comment]
Looks good to me, thanks @rhoads-zach
