### ISSUE TITLE
SpringBoot, VertX, Swarm booster chapters - note about code download

### ISSUE THREAD

**Issue by liborfuka** [openshiftio/appdev-documentation#616]
There should be some note at the beginning of every mission chapter where to download code what is chapter about.
For example 'Code can be downloaded from launchpad...select booster xy and download the code in zip....

Just to know and see code what is chapter about.

**Comment by inoxx03** [comment]
@liborfuka We could add a link to the [Launcher](launch.openshift.io/wizard) at the top of each mission  section. Accessing the launcher, however, requires early access, so users must first request access to the launcher in order to be able to Download the ZIP file and preview the code.
Another alternative would be to provide a link directly to the Git Hub repo that hosts the code for each individual booster. users could download the ZIP files from there, too. WDYT?

**Comment by inoxx03** [comment]
IIUC, a similar workflow is described in the Getting Started Guide, [section 1}(https://appdev.openshift.io/docs/getting-started.html#oso-create-booster). 
Did you mean something like this?

**Comment by liborfuka** [comment]
Yes, its enough, just something like that for specific booster. Thank you.
